version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    environment:
      PORT: 8080
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./src/public:/var/www/html
      - ./volumes/development/nginx:/etc/nginx/conf.d
      - ./volumes/production/certbot/conf:/etc/letsencrypt
      - ./volumes/production/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./volumes/production/certbot/conf:/etc/letsencrypt
      - ./volumes/production/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    # opens all ports between containers on the same bridge network, 
    driver: bridge 
