version: "3.7"

services:
  nodejs:
    container_name: nodejs
    build: ./
    volumes:
      - "./:/usr/src/app"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    command: node server
    restart: unless-stopped
    networks:
    # Opens all ports between containers on the same bridge network
      - app-network

  webserver:
    container_name: webserver
    image: nginx:mainline-alpine
    ports: 
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    restart: unless-stopped
    networks:
      - app-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - web-root::/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email username@email.com

