version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    environment:
      PORT: 8080
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: $PUBLIC_DIR
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: $DH_DIR
      o: bind

networks:
  app-network:
    # opens all ports between containers on the same bridge network, 
    driver: bridge 