version: "3.7"

services:
  node_server:
    container_name: node_server
    build: ./
    volumes:
      - "./:/usr/src/app"
    environment:
      DOMAIN: example.com
      HTTP_PORT: 80
      HTTPS_PORT: 443
    command: node server
