version: '3'

services:
  nodejs:
    image: node:10
    environment:
      PORT: 8080
    restart: unless-stopped
    volumes:
      - "./:/app"
    working_dir: /app
    networks:
      - app-network
    command: node src/server.js

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./src/public:/var/www/html
      - ./volumes/${mode-development}/nginx:/etc/nginx/conf.d
      - ./volumes/${mode-development}/certbot/conf:/etc/letsencrypt
      - ./volumes/${mode-development}/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./volumes/${mode-development}/certbot/conf:/etc/letsencrypt
      - ./volumes/${mode-development}/certbot/www:/var/www/certbot

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    # opens all ports between containers on the same bridge network, 
    driver: bridge 
