version: "3.7"

services:
  node_app:
    container_name: node_app
    build: ./
    volumes:
      - "./:/usr/src/app"
    ports:
      - "80:80"
    environment:
      PORT: 80
    command: node server
