version: "3.7"

services:
  node_app:
    container_name: node_app
    build: ./
    volumes:
      - "./:/usr/src/app"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    command: node server
